<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../buildprops/Directory.Build.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PsdParser" Version="1.2.2" />
  </ItemGroup>

</Project>
